[toolchain]
channel = "nightly-2025-07-22"
# components = [ "rustfmt", "rustc-dev", "clippy" ]
# targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "wasm32-unknown-unknown" ]
# profile = "minimal"
